## 3.1 Introduction to Python

- Python supports multi-dimensional arrays and matrices
 - n-dimensional arrays (ndarray)
   - fast, efficient way of storing homogeneous data (data of the same type)
   - 1-dimensional arrays AKA rank 1 arrays
 - Can have many rows and columns
 - Created using `np.array(List)` where "`List`" is just a normal python list
 
- An array of Zeros can be created using `np.zeros(m, n)` where `m` and `n` are integer values representing the number of rows and columns to create
- Similarly, create an array full of a number using `np.full((m,n), i)` where `i` is the number to fill the array
- `np.eye(m,n)` creates an identity matrix

In [1]:
import numpy as np

In [13]:
# creating rank 1 arrays

arr1 = [1, 2, 3, 4, 5, 6] # list
nd_arr1 = np.array(arr1) # array

# creating n-dimensional arrays
arr2 = [[1, 2], [3,4]]
nd_arr2 = np.array(arr2)

# create array of zeros, array of 5s, and 2x2 identity matrix
nd_zeros = np.zeros((2,2))
nd_fives = np.full((2,2), 5)
nd_eye = np.eye(2,2)
nd_eye

array([[1., 0.],
       [0., 1.]])

# 3.2 Numpy Operations

### Python Indexing

- Arrays index from 0 going left to right
- Arrays index from -1 going right to left

In [14]:
print(arr1[0]) # prints first element of arr1
print(arr1[-1]) # prints last element of arr1


1
6


---
- Can isolate entire chunk of list using `[i:j]` indexing
 - jth index is non-inclusive
   - e.g. `arr1[0:2]` will return `[1,2]`
- Can also iterate in steps of k using `[i:j:k]` and use negative indices

In [18]:
print(nd_arr1[0:2]) 
print(nd_arr1[0:4:2]) # will not include index 4 (5)
print(nd_arr1[-3:-1]) # prints last two digits

[1 2]
[1 3]
[4 5]


---
Two arrays can be concatenated together using `np.concatenate(arr_list)`

In [19]:
nd_arr3 = np.array([7, 8, 9])
np.concatenate([nd_arr1, nd_arr3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

---
- Indexing multi-dimensional array:
 - `ndarray[i, j]` will return row i, column j
 - `ndarray[i]` will return row i
- Can replace value in an element by setting it equal to a ne w value
- Can also index groups of an ndarray using the same technique as indexing blocks of 1d arrays
- np.concatenate will default to concatenating rows
 - can using "index" argument to change this behaviour
 - Must have same number of columns

In [22]:
print(nd_arr2[1,1]) # prints element at position 1, 1
nd_arr2[1,1] = 19 # replaces element at position 1, 1 with 19

print(nd_arr2[0:2, 0:2]) # index chunk of nd array

19
[[ 1  2]
 [ 3 19]]


--- 
## Matrix Arithmetic and Linear Algebra
